/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.FaceLivenessDetection.Sdk {

public enum FLD_SDK_IMAGE_TYPE {
  FLD_SDK_IMAGE_TYPE_RGB24,
  FLD_SDK_IMAGE_TYPE_RGBA32,
  FLD_SDK_IMAGE_TYPE_BGRA32,
  FLD_SDK_IMAGE_TYPE_BGR24,
  FLD_SDK_IMAGE_TYPE_NV12,
  FLD_SDK_IMAGE_TYPE_NV21,
  FLD_SDK_IMAGE_TYPE_YUV420P,
  FLD_SDK_IMAGE_TYPE_YVU420P,
  FLD_SDK_IMAGE_TYPE_YUV422P,
  FLD_SDK_IMAGE_TYPE_YUV444P,
  FLD_SDK_IMAGE_TYPE_Y
}

}
