/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.FaceLivenessDetection.Sdk {

using System;
using System.Runtime.InteropServices;

public class FldSdkResult : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FldSdkResult(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(FldSdkResult obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~FldSdkResult() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          FaceLivenessDetectionSDKPINVOKE.delete_FldSdkResult(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public FldSdkResult() : this(FaceLivenessDetectionSDKPINVOKE.new_FldSdkResult__SWIG_0(), true) {
  }

  public FldSdkResult(int code, string phrase, string json, uint numFaces) : this(FaceLivenessDetectionSDKPINVOKE.new_FldSdkResult__SWIG_1(code, phrase, json, numFaces), true) {
  }

  public FldSdkResult(int code, string phrase, string json) : this(FaceLivenessDetectionSDKPINVOKE.new_FldSdkResult__SWIG_2(code, phrase, json), true) {
  }

  public FldSdkResult(FldSdkResult other) : this(FaceLivenessDetectionSDKPINVOKE.new_FldSdkResult__SWIG_3(FldSdkResult.getCPtr(other)), true) {
    if (FaceLivenessDetectionSDKPINVOKE.SWIGPendingException.Pending) throw FaceLivenessDetectionSDKPINVOKE.SWIGPendingException.Retrieve();
  }

  public int code() {
    int ret = FaceLivenessDetectionSDKPINVOKE.FldSdkResult_code(swigCPtr);
    return ret;
  }

  public string phrase() {
    string ret = FaceLivenessDetectionSDKPINVOKE.FldSdkResult_phrase(swigCPtr);
    return ret;
  }

  public string json() {
    string ret = FaceLivenessDetectionSDKPINVOKE.FldSdkResult_json(swigCPtr);
    return ret;
  }

  public uint numFaces() {
    uint ret = FaceLivenessDetectionSDKPINVOKE.FldSdkResult_numFaces(swigCPtr);
    return ret;
  }

  public bool isOK() {
    bool ret = FaceLivenessDetectionSDKPINVOKE.FldSdkResult_isOK(swigCPtr);
    return ret;
  }

}

}
