/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.FaceLivenessDetection.Sdk;

public class FldSdkResult {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FldSdkResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FldSdkResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FaceLivenessDetectionSDKJNI.delete_FldSdkResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FldSdkResult() {
    this(FaceLivenessDetectionSDKJNI.new_FldSdkResult__SWIG_0(), true);
  }

  public FldSdkResult(int code, String phrase, String json, long numFaces) {
    this(FaceLivenessDetectionSDKJNI.new_FldSdkResult__SWIG_1(code, phrase, json, numFaces), true);
  }

  public FldSdkResult(int code, String phrase, String json) {
    this(FaceLivenessDetectionSDKJNI.new_FldSdkResult__SWIG_2(code, phrase, json), true);
  }

  public FldSdkResult(FldSdkResult other) {
    this(FaceLivenessDetectionSDKJNI.new_FldSdkResult__SWIG_3(FldSdkResult.getCPtr(other), other), true);
  }

  public int code() {
    return FaceLivenessDetectionSDKJNI.FldSdkResult_code(swigCPtr, this);
  }

  public String phrase() {
    return FaceLivenessDetectionSDKJNI.FldSdkResult_phrase(swigCPtr, this);
  }

  public String json() {
    return FaceLivenessDetectionSDKJNI.FldSdkResult_json(swigCPtr, this);
  }

  public long numFaces() {
    return FaceLivenessDetectionSDKJNI.FldSdkResult_numFaces(swigCPtr, this);
  }

  public boolean isOK() {
    return FaceLivenessDetectionSDKJNI.FldSdkResult_isOK(swigCPtr, this);
  }

}
