/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.FaceLivenessDetection.Sdk;

public class FldSdkParallelDeliveryCallback {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FldSdkParallelDeliveryCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FldSdkParallelDeliveryCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FaceLivenessDetectionSDKJNI.delete_FldSdkParallelDeliveryCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void onNewResult(FldSdkResult newResult) {
    FaceLivenessDetectionSDKJNI.FldSdkParallelDeliveryCallback_onNewResult(swigCPtr, this, FldSdkResult.getCPtr(newResult), newResult);
  }

}
